Code
sbtsamara/xslt-generator pull request #1
Opened 2017-06-30 11:44 UTC by SaushkinDenis

2017-06-30 11:54 UTC, sbtsamara commented on Generator/src/generator/Generator.java
> +            case "ЦИКЛ":
Все эти значения (ЦИКЛ, УСЛОВИЕ и т.д.) нужно вынести в словарь - это должен быть либо интерфейс с константами, либо конфиг. Лучше конфиг, чтобы этот словарь можно было настраивать, не меняя код программы.

2017-06-30 11:54 UTC, sbtsamara commented on Generator/src/generator/Generator.java
> +        String[] COP = readLine();
Капслоком называем только константы.
Изучи соглашения по кодированию на Java: 
http://www.oracle.com/technetwork/java/codeconvtoc-136057.html

2017-06-30 11:54 UTC, sbtsamara commented on Generator/src/generator/Generator.java
> +    public static void main(String[] args) {
Метод main вынеси в отдельный класс, через который будет запускаться твоя утилита.

2017-06-30 11:54 UTC, sbtsamara commented on Generator/src/generator/Generator.java
> +        String[] COP = readLine();
И сделай публичными только те методы, которые будут вызываться снаружи класса. Остальные методы должны быть приватными.

2017-07-03 14:02 UTC, SaushkinDenis commented
Made new class

2017-07-05 07:52 UTC, sbtsamara requested changes
Сделай новый pull request  с последними изменениями

2017-07-05 13:13 UTC, SaushkinDenis commented
Отправил через новый branch. 
Добавили функции в псевдокод  https://docs.google.com/document/d/1L5G1I2PBCr4pQWoNTIZndyDMCr9UpLfhjYGu2W6_uCo/edit  
Для примера, в JSon прописали функцию "РАЗМЕР" и добавили проверку атрибута на содержание в Json. 

-- 
С уважением, Denis Saushkin

2017-07-20 20:57 UTC, closed without merging

2017-07-20 20:57 UTC, sbtsamara commented
Не актуальный.