Generator
sbtsamara/xslt-generator pull request #2
Opened 2017-07-05 10:04 UTC by SaushkinDenis

2017-07-07 07:42 UTC, sbtsamara commented on Generator/src/generator/Creator.java
> +
Удали лишние пустые строки и приведи всё к единому стилю оформления кода.
Ещё раз: ориентируйся на Java Code Conventions

2017-07-07 07:42 UTC, sbtsamara commented on Generator/src/generator/Creator.java
> +        File dir = new File("C://Users//usersbt//Downloads//File.xsl");
Пути, настройки и т.п. нужно вынести в файл конфига приложения

2017-07-07 07:43 UTC, sbtsamara commented on Generator/src/generator/Creator.java
> +        {
Оформление блока не по Java Code Conventions

2017-07-07 07:44 UTC, sbtsamara commented on Generator/src/generator/Creator.java
> +        catch(IOException ex){  System.out.println(ex.getMessage());}
Аналогично - некорректное оформление блока.
System out нужно везде заменить на логгер (например, на slf4j) - добавьте в TODO

2017-07-07 07:45 UTC, sbtsamara commented on Generator/src/generator/Generator.java
> +   // public static final String PATH_TO_PROPERTIES = "src/resources/config.properties";
Закомментированный код коммитить не нужно.

2017-07-07 07:46 UTC, sbtsamara commented on Generator/src/generator/Json.json
> +{
Оформите с нормальными отступами структуру, иначе её потом сложно будет править.

2017-07-07 07:46 UTC, sbtsamara commented on Generator/src/generator/WorkJson.java
> +    private static final String FILENAME = "C:\\Users\\usersbt\\Documents\\NetBeansProjects\\xslt-generator\\Generator\\src\\generator\\Json.json";
Вынести в конфиг

2017-07-07 07:48 UTC, sbtsamara requested changes
Исправьте по замечаниям

2017-07-10 13:27 UTC, SaushkinDenis commented
Написали 3 простых теста. Тест с json не проходит (только с отладкой).

2017-07-11 13:42 UTC, SaushkinDenis commented
Проблему с тестом Json не исправили, изменили код, добавили возможность ввода нескольких операций.

2017-07-12 13:28 UTC, SaushkinDenis commented
Исправили проблему с тестом Json.

2017-07-20 21:01 UTC, sbtsamara approved these changes

2017-07-20 21:01 UTC, merged